kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config
  namespace: sandesh

data:
  MYSQL_URI: "mysql://root:admin@db-svc:3306/devops"
  MYSQL_HOST: "db-svc"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "admin"
  MYSQL_DB: "devops"
