name: test-deployment

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Google Cloud ke sath secure connection banana
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2. Bina manually key manage kiye GCP VM par command chalana
      - name: Deploy to GCP VM via Google SSH
        uses: google-github-actions/ssh-compute@v1
        with:
          instance_name: instance-20260826-152012  # <-- Apne VM ka exact naam check kar lein
          zone: us-central1-a                        # <-- Apne VM ka sahi Zone dalein (jaise us-central1-a, asia-south1-a)
          ssh_private_key: ${{ secrets.KEY }}        # Aapki banayi hui private key
          command: |
            sudo bash -c "
              # 1. Sahi project directory mein jayein
              cd /home/sandeshsaini7983637650/github/two-tier-flask-app || cd /root/github/two-tier-flask-app
              
              # 2. Git ko clean aur fresh karne ke liye remote wapas clean setup karein
              git remote remove origin 2>/dev/null || true
              git remote add origin https://github.com
              
              # 3. GitHub se saari branches ki taaza information khinchein
              git fetch --all --prune
              
              # 4. Local branches ka lafda khatam karke direct origin/main par overwrite karein
              git checkout -B main origin/main || git checkout -B master origin/master
              git reset --hard origin/main || git reset --hard origin/master
              
              # 5. Docker Containers ko naye code ke sath build aur up karein
              docker compose up -d --build
            "



      
